AllCops:
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.5
  Exclude:
    - data/**/*

Layout/LineLength:
  Enabled: true
  Max: 130

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Max: 25
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - ./*.gemspec

Metrics/CyclomaticComplexity:
  Max: 9
#  Exclude:

Metrics/PerceivedComplexity:
  Max: 11
#   Exclude:

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - exe/**/*

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
