version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node
    executor: ruby/default
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run:
          name: Install Dependencies
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler:$BUNDLER_VERSION
            bundle install --jobs 4 --retry 3
      - restore_cache:
          name: Restore bundle cache
          keys:
            - v2-himawari-bundle-{{ checksum "Gemfile.lock" }}-{{ arch }}
            - v2-himawari-bundle-
      - save_cache:
          name: Store bundle cache
          key: v2-himawari-bundle-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: .
          paths:
            - vendor/bundle

  rubocop:
    docker:
      - image: circleci/ruby:2.5.1-node
        environment:
          BUNDLE_PATH: vendor/bundle
    executor: ruby/default
    steps:
      - attach_workspace:
          at: .
      - run:
          command: bundle exec rubocop
