version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-node
        environment:
          BUNDLE_PATH: vendor/bundle
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            bundle -v
      - run:
          name: rubocop
          command: bundle exec rubocop
