version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

executors:
  super-ruby:
    docker:
      - image: cimg/ruby:2.5-node
        environment:
          BUNDLE_PATH: vendor/bundle
          CUSTOM_VAR: whatever

jobs:
  checkout_code:
    executor: super-ruby
    steps:
      - attach_workspace:
          at: .
      - checkout
      - ruby/install-deps:
        path: $BUNDLE_PATH
      - persist_to_workspace:
          root: .
          paths: .

  build:
    executor: super-ruby
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          name: Restore bundle cache
          keys:
            - v2-himawari-bundle-{{ checksum "Gemfile.lock" }}-{{ arch }}
            - v2-himawari-bundle-
      - run:
          name: Install Important Stuff
          command: |
            bundle install --jobs 4 --retry 3
            echo 'installing!'
            echo $CUSTOM_VAR
            ls -al
      - save_cache:
          name: Store bundle cache
          key: v2-himawari-bundle-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: .
          paths:
            - vendor/bundle

  rubocop:
    executor: super-ruby
    steps:
      - attach_workspace:
          at: .
      - run: bundle exec rubocop

  bundle_audit:
    executor: super-ruby
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Bundle Audit
          when: always
          command: |
            bundle -v
            ls -la $BUNDLE_PATH/gems
            gem install bundle-audit && bundle-audit update && bundle-audit check

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - bundle_audit:
          requires:
            - checkout_code
      - rubocop:
          requires:
            - build
