version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-node
        environment:
          BUNDLE_PATH: vendor/bundle
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler:2.1.4
            echo $BUNDLER_VERSION
            bundle -v
            bundle install --path vendor/bundle --jobs 4 --retry 3
      - run:
          name: rubocop
          command: |
            bundle --path vendor/bundle
            bundle exec rubocop
