version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-stretch-node
        environment:
          BUNDLE_PATH: vendor/bundle
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Install Dependencies
          command: |
            gem update --system
            gem install bundler
      - run:
          name: Set bundle path
          command: |
            bundle --path vendor/bundle
            bundle -v
      - run:
          command: bundle install
      - run:
          command: bundle exec rubocop
